<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>14</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>747.0102685992244</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>174.71584681264002</KnownMass>
                    <Density>2075.992848</Density>
                    <Material>WM FG</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>174.71584681264002</CalcMass>
                    <CalcCG>238.49425027273372</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>381.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>56.946799999999996</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>18.204629430626163</KnownMass>
                    <Density>2075.992848</Density>
                    <Material>WM FG</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>18.204629430626163</CalcMass>
                    <CalcCG>12.7</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>25.4</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>56.946799999999996</OD>
                    <ID>52.9468</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>52.9468</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <BodyTube>
                    <KnownMass>344.26842459915565</KnownMass>
                    <Density>1780.0</Density>
                    <Material>Carbon fiber</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>344.26842459915565</CalcMass>
                    <CalcCG>482.59999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>965.1999999999999</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>3</SerialNo>
                    <OD>56.946799999999996</OD>
                    <ID>54.6608</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>54.6608</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>83.16225257152816</KnownMass>
                            <Density>2075.992848</Density>
                            <Material>WM FG</Material>
                            <Name>Tube Coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-63.5</Xb>
                            <CalcMass>83.16225257152816</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>54.61</OD>
                            <ID>50.8</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>11.945312127549071</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>335.28</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>335.28</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>19.049999999999997</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>139.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>11.945312127549071</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>335.28</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>335.28</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>19.049999999999997</RadialLoc>
                            <RadialAngle>3.141592653589793</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>139.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>17.85763833209356</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>409.2575</Xb>
                            <CalcMass>17.85763833209356</CalcMass>
                            <CalcCG>2.3812499999999996</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>4.762499999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>50.8</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>200.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>203.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>203.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>4.343749864563299</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>457.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>457.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>136.07771616</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>-157.48000000000002</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-157.48000000000002</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>68.70495540058721</KnownMass>
                            <Density>0.00527</Density>
                            <Material>Nylon fabric, ripstop, 1.7 oz actual</Material>
                            <Name>Parachute, 45 in., nylon, 8 lines</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-96.52</Xb>
                            <CalcMass>68.70495540058721</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.2295950247709575</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>1143.0</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1143.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>0.0</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>123.6801111436942</CalcMass>
                    <CalcCG>114.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>228.6</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>56.946799999999996</OD>
                    <ID>54.6608</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>54.6608</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>341.55505461</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>179.62259574918528</CalcMass>
                            <CalcCG>141.95412565380394</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>13</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>228.6</RootChord>
                            <TipChord>38.099999999999994</TipChord>
                            <SemiSpan>50.8</SemiSpan>
                            <SweepDistance>177.79999999999998</SweepDistance>
                            <Thickness>2.54</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>89.3</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>34.2</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>28.037356575948586</CalcMass>
                    <CalcCG>15.920703728895205</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>33.147</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>14</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>56.946799999999996</FrontDia>
                    <RearDia>45.339</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>